# Generated by Django 5.2.3 on 2025-07-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCategory',
            fields=[
                ('field_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('related_majors', models.TextField()),
                ('entry_path', models.TextField()),
                ('keyword_tags', models.CharField(max_length=200)),
                ('recommend_reason', models.TextField()),
                ('stem_category', models.CharField(max_length=100)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.fieldcategory')),
                ('related_tags', models.ManyToManyField(to='jobs.interesttag')),
            ],
        ),
    ]
