# Generated by Django 5.2.3 on 2025-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_userlikedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikedjob',
            name='stem_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
