# Generated by Django 5.2.3 on 2025-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_userlikedjob_stem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
