# Generated by Django 5.2.3 on 2025-07-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('related_majors', models.TextField()),
                ('entry_path', models.TextField()),
                ('keyword_tags', models.TextField()),
                ('recommend_reason', models.TextField()),
                ('stem_category', models.CharField(max_length=100)),
                ('field_id', models.CharField(max_length=10)),
                ('field_name', models.CharField(max_length=100)),
                ('related_tags', models.ManyToManyField(to='match.interesttag')),
            ],
        ),
    ]
