# Generated by Django 5.2.3 on 2025-07-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_userselectedtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Soft_Skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='emotive_copy',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
